language: ruby
dist: xenial

rvm:
  - 2.7

services:
  - postgresql

before_install:
  - sudo apt-get install -y postgresql-server-dev-9.2
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get install ruby-rspec-core
  
script:
  - bundle exec rspec
