language: ruby
dist: xenial

rvm:
  - 2.7

services:
  - postgresql

before_install:
  - gem install bundler
  - sudo apt-get update
  - sudo apt-get install ruby-rspec-core
  - git clone https://github.com/travis-ci/travis-build.git
  - cd travis-build
  - bundler
  - bundler binstubs travis
  - bin/travis compile

  
script:
  rspec
